---
title: "Create your Mamba environment and install software"
author: "Gabriel Ortega-Solís"
execute:
  eval: false
---

# Request Interactive Session

Run this command from a login node to request an interactive PBS session:
```bash
qsub -I \
  -N mamba_setup \
  -l select=1:ncpus=1:mem=16gb \
  -l walltime=02:00:00 \
  -j oe
```

# Run Environment Setup Inside the Interactive Session

After PBS allocates the node and you see the interactive shell prompt, run:
```bash
module add mambaforge
mamba create -n geostatistics2 -c conda-forge "r-terra>=1.8"
```

The code above will install R as a "side effect" of installing version 1.8 or higher of the `terra` package. You can replace `r-terra` with any other package you want to install, and Mamba will automatically resolve and install the necessary dependencies. Alternatively, you could just create an empty environment running `mamba create -n SOME_NAME` and then install packages one by one or in groups as needed.

# Activate the environment
```bash
mamba activate geostatistics2
```

# Install more packages
You can install more packages in the same environment. For python , just replace the package name after *conda-forge* with the one you want to install. For R packages you have to write r-PACKAGE_NAME. 
```bash
mamba install -c conda-forge geopandas r-sf
```

# Deactivate the environment when you are done
```bash
mamba deactivate
```
