project:
  type: book
  output-dir: docs

book:
  title: "Preparing and submitting a job to a HPC cluster"
  author: "Gabriel Ortega-Solís"
  date: today
  chapters:
    - index.qmd
    - 1_disable_automatic_terminals.qmd
    - 2_HPC_setup.qmd
    - 3_submit_a_job.qmd
    - 4_vscode_metacentrum_setup.qmd

execute:
  echo: true

format:
  html:
    theme: cosmo
    code-block-bg: true
    code-copy: true
