project:
  type: book
  output-dir: docs

book:
  title: "Preparing and submitting a job to a HPC cluster"
  author: "Gabriel Ortega-Solís"
  date: today
  chapters:
    - index.qmd
    - 1_HPC_setup.qmd
    - 2_submit_a_job.qmd

execute:
  echo: true

format:
  html:
    theme: darkly
    code-block-bg: true
    code-copy: true
